# Generated by Django 3.1 on 2026-06-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20260616_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
