# Generated by Django 3.1 on 2026-06-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20260616_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
