# Generated by Django 3.1 on 2026-06-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20260616_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
